baseURL = "https://estihlalkwt.com/"
languageCode = "en-us"
title = "اللجنة الكويتية المشتركة للاستهلال"
summaryLength = 10
preserveTaxonomyNames = true

[permalinks]
  blog = "/:filename"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "الصفحة الرئيسية"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "رصد الاهلة"
    pre = "moon"
    url = "/crescents/"
    weight = 2
  # [[menu.main]]
  #   name = "ألبوم الصور"
  #   pre = "camera"
  #   url = "/about/under-construction/"
  #   weight = 3
  [[menu.main]]
    name = "كيفية الرصد"
    pre = "eye"
    url = "/about/observation/"
    weight = 4
  [[menu.main]]
    name = "من نحن"
    pre = "users"
    url = "/about/us/"
    weight = 5

[taxonomies]
  tag = "tags"


[params]
  dateFormat = "Jan 2, 2006"
  homeText = "لجنة غير ربحية معنية بالاستهلال والمواقيت الشرعية"
  donate = "اللجنة تطوعية بالكامل وبحاجة الى دعمكم للاستمرار بتوفير خدماتها."
