backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "ads"
    label: "اعلان"
    folder: content/ads
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "تاريخ انتهاء الصلاحية", name: "adExpiryDate", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list"}
      - {label: "المتن", name: "body", widget: "markdown"}
  - name: "showntell"
    label: "صورة وتعليق"
    folder: content/showntell
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "التعليق", name: "body", widget: "markdown"}
  - name: "news"
    label: "خبر"
    folder: content/news
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list"}
      - {label: "المتن", name: "body", widget: "markdown"}
  - name: "astroFlash"
    label: "اضاءة فلكية"
    folder: content/astroFlash
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list"}
      - {label: "الكاتب", name: "author", widget: "string"}
      - {label: "المتن", name: "body", widget: "markdown"}
  - name: "crescents"
    label: "رصد الاهلة"
    folder: content/crescents
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "الشهر الهجري", name: "hijryMonth", widget: "select", options: ["محرم", "صفر", "ربيع الاول", "ربيع الاخر", "جمادى الاولى", "جمادى الاخرة", "رجب", "شعبان", "رمضان", "شوال", "ذو القعدة", "ذو الحجة"]}
      - {label: "السنة الهجرية", name: "hijryYear", widget: "number", default: 1440, valueType: "int", min: 1440, max: 1500}
      - {label: "اليوم الاول", name: "firstDayName", widget: "select", options: ["السبت", "الاحد", "الاثنين", "الثلاثاء", "الاربعاء", "الخميس", "الجمعة"]}
      - {label: "تاريخ اليوم الاول", name: "firstDayDate", widget: "string", default: "DD/MM/YYYY"}
      - {label: "شرح تفاصيل الرصد", name: "body", widget: "markdown"}
      - {label: "الصائغ رسم الهلال", name: "sayeghImg1", widget: "image", allow_multiple: false}
      - {label: "الصائغ جدول المدن", name: "sayeghImg2", widget: "image", allow_multiple: false}
      - {label: "عودة اللية الاولى", name: "odahImg1", widget: "image", allow_multiple: false}
      - {label: "عودة اللية الثانية", name: "odahImg2", widget: "image", allow_multiple: false}
      - {label: "يالوب اللية الاولى", name: "yallopImg1", widget: "image", allow_multiple: false}
      - {label: "يالوب اللية الثانية", name: "yallopImg2", widget: "image", allow_multiple: false}
      - {label: "شوكت اللية الاولى", name: "shawkatImg1", widget: "image", allow_multiple: false}
      - {label: "شوكت اللية الثانية", name: "shawkatImg2", widget: "image", allow_multiple: false}
      - {label: "موقع عودة", name: "odahHTML", widget: "string", default: "http://www.icoproject.org/icop.html"}
      - {label: "موقع يالوب", name: "yallopHTML", widget: "string", default: "http://astro.ukho.gov.uk/moonwatch/index.html"}
      - {label: "موقع شوكت", name: "shawkatHTML", widget: "string", default: "https://www.moonsighting.com/"}
  - name: "announcements"
    label: "اعلان استهلال"
    folder: content/announcements
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "تاريخ انتهاء الصلاحية", name: "expDate", widget: "datetime"}
      - {label: "قرار الخروج للاستهلال", name: "announce", widget: "select", default: "ستخرج", options: ["ستخرج","لن تخرج"]}
      - {label: "الشهر الهجري", name: "hijryMonth", widget: "select", options: ["محرم", "صفر", "ربيع الاول", "ربيع الاخر", "جمادى الاولى", "جمادى الاخرة", "رجب", "شعبان", "رمضان", "شوال", "ذو القعدة", "ذو الحجة"]}
      - {label: "السنة الهجرية", name: "hijryYear", widget: "number", default: 1442, valueType: "int", min: 1440, max: 1500}
      - {label: "يوم الاستهلال", name: "dayOfSighting", widget: "select", options: ["السبت", "الاحد", "الاثنين", "الثلاثاء", "الاربعاء", "الخميس", "الجمعة"]}
      - {label: "تاريخ يوم الاستهلال", name: "dateOfSighting", widget: "string", default: "YYYY/MM/DD"}
      - {label: "المكان", name: "location", widget: "string"}
      - {label: "المنطقة", name: "area", widget: "string"}
      - {label: "وقت الغروب", name: "sunset", widget: "string"}
      - {label: "عمر الهلال (ساعة)", name: "age", widget: "string"}
      - {label: "اضاءة الهلال (بالمائة)", name: "illumination", widget: "string"}
      - {label: "ارتفاع الهلال (درجة)", name: "altitude", widget: "string"}
      - {label: "مكث الهلال (دقيقة)", name: "stay", widget: "string"}
      - {label: "البعد الزاوي (درجة)", name: "elongation", widget: "string"}
      - {label: "امكانية رؤية الهلال", name: "verdict", widget: "string"}
      - {label: "بيان الاستهلال", name: "report", widget: "select", default: "لم تخرج بعد", options: ["لم تخرج بعد","وقد تمكنت من رؤية الهلال بالعين المجردة وبالمناظير.","وقد تمكنت من رؤية الهلال بالمناظير فقط.","ولم تتمكن من رؤية الهلال لا بالعين المجردة ولا بالمناظير."]}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list"}
  - name: "events"
    label: "حدث فلكي"
    folder: content/events
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "select", options: ["خسوف جزئي","خسوف كلي","خسوف ظليلي","كسوف جزئي","كسوف كلي","كسوف حلقي"]}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list", default: ["خسوف","كسوف"], allow_add: true}
      - {label: "الصورة", name: "image", widget: "select", options: ["images/lunar-partial.jpg","images/lunar-total.jpg","images/solar-partial.jpg","images/solar-total.jpg","images/solar-ring.jpg"]}
      - {label: "تاريخ الحدث", name: "eventDate", widget: "date"}
      - {label: "وصف مختصر للحدث", name: "description", widget: "string"}
      - {label: "وصف تفاصيل الحدث", name: "body", widget: "markdown"}
  - name: "articles"
    label: "مقال"
    folder: content/articles
    create: true
    slug: "{{year}}{{month}}{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "المؤلف", name: "author", widget: "string"}
      - {label: "وسوم", name: "tags", widget: "list"}
      - {label: "نص المقال", name: "body", widget: "markdown"}
  - name: "links"
    label: "رابط علمي"
    folder: content/links
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الرابط", name: "link", widget: "string"}
      - {label: "الترتيب", name: "weight", widget: "number"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}

