backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
# publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "news"
    label: "خبر"
    folder: content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list"}
      - {label: "المتن", name: "body", widget: "markdown"}
  - name: "ads"
    label: "اعلان"
    folder: content/ads
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "تاريخ انتهاء الصلاحية", name: "adExpiryDate", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "وسوم", name: "tags", widget: "list"}
      - {label: "المتن", name: "body", widget: "markdown"}
  - name: "crescents"
    label: "رصد الاهلة"
    folder: content/crescents
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "مسودة", name: "draft", widget: "select", default: "false", options: ["true","false"]}
      - {label: "الشهر الهجري", name: "hijryMonth", widget: "select", options: ["محرم", "صفر", "ربيع الاول", "ربيع الاخر", "جمادى الاولى", "جمادى الاخرة", "رجب", "شعبان", "رمضان", "شوال", "ذو القعدة", "ذو الحجة"]}
      - {label: "السنة الهجرية", name: "hijryYear", widget: "number", default: 1440, valueType: "int", min: 1440, max: 1500}
      - {label: "اليوم الاول", name: "firstDayName", widget: "select", options: ["السبت", "الاحد", "الاثنين", "الثلاثاء", "الاربعاء", "الخميس", "الجمعة"]}
      - {label: "تاريخ اليوم الاول", name: "firstDayDate", widget: "date"}
      - {label: "الصائغ رسم الهلال", name: "sayeghImg1", widget: "image", allow_multiple: "false"}
      - {label: "الصائغ جدول المدن", name: "sayeghImg2", widget: "image", allow_multiple: "false"}
      - {label: "عودة اللية الاولى", name: "odahImg1", widget: "image", allow_multiple: "false"}
      - {label: "عودة اللية الثانية", name: "odahImg2", widget: "image", allow_multiple: "false"}
      - {label: "يالوب اللية الاولى", name: "yallopImg1", widget: "image", allow_multiple: "false"}
      - {label: "يالوب اللية الثانية", name: "yallopImg2", widget: "image", allow_multiple: "false"}
      - {label: "شوكت اللية الاولى", name: "shawkatImg1", widget: "image", allow_multiple: "false"}
      - {label: "شوكت اللية الثانية", name: "shawkatImg2", widget: "image", allow_multiple: "false"}
      - {label: "شرح تفاصيل الرصد", name: "body", widget: "markdown"}
      - {label: "موقع عودة", name: "odahHTML", widget: "string", default: "http://www.icoproject.org/icop.html"}
      - {label: "موقع يالوب", name: "yallopHTML", widget: "string", default: "http://astro.ukho.gov.uk/moonwatch/index.html"}
      - {label: "موقع شوكت", name: "shawkatHTML", widget: "string", default: "https://www.moonsighting.com/"}

